### ISSUE TITLE
Photos views styling

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#133]
### Describe the bug
- Spacing between the photos in a photo album is different from other views
- Opening an album uses some kind of transition that where you need a shared view (like an image) for, instead of just opening the view. But this transition is not used when opening a photo in an album, where it would be perfect.
- A photo detail view closes when you swipe down for no clear reason, this interferes with the zooming gestures that are in the same view.
- The buttons in the toolbar of the photo detail view are located in different spots than the album overview toolbar.

### How to reproduce
1. Go to the photo albums functionality

**Comment by se-bastiaan** [comment]
I think I gave you enough resources to try to understand consistency. Seems you didn't read them.

**Comment by se-bastiaan** [comment]
I answer like that because my comments get 0 response. The issues are just closed without any argumentation.
But maybe it is good to mention too that the progress has been awesome and a lot of things have been fixed.

Why not just follow the guidelines set by people that have so much more experience in these kinds of things than any of us? Why is our implementation better?

And if we think the larger grid items are better, then why not just make the grid the same (larger) size in every screen? That usually makes it easier to re-use the component and their styling, isn't that also true for Flutter?

I simply don't understand the choices without any context and that really feels like parts of comments are just thrown away.

**Comment by DeD1rk** [comment]
> I answer like that because my comments get 0 response. The issues are just closed without any argumentation.

I'm sorry it feels that way. You can be sure any point we don't do as you said has been discussed live, so there is always some reason, but I'll be sure to make those more explicit here as well. 

I agree that it's best to follow guidelines where possible, but there are sometimes just cases where guidelines don't apply perfectly. 

For the grids, I think it makes sense to have quite average spacing around the tiles that navigate to some other screen (the ones with the gradient and text on it). For the images, so much spacing just looks weird because the image is the main content, not just decoration for a name/button. I've actually looked into various spacings for the albums, and think it would be sensible to go for even smaller spacing (2px), which will look more clearly like a distinction based on the content, but I'll show around the options again Monday.

So yes regarding the padding, we'll take another look next week.
And regarding communication, I'll write down some more background when we make choices, and you can be sure that I've read the material design guide entirely. I hope then you'll feel that we really do take everything you say into account.

**Comment by DeD1rk** [comment]
Did a vote-ish thing here and determined we'd go with the 8px as you want. It's updated on master.
