### ISSUE TITLE
Event Registrations is limited to 50

### ISSUE THREAD

**Issue by TippieCodes** [svthalia/Reaxit#146]
### Describe the bug
The event registrations only display the first 50 registered members rather than all.

### How to reproduce
1. Log in to the app
2. Go to an event where more than 50 people have registered
3. Count the number of registered members displayed and observe.

### Expected behavior
All members that have registered for this event should show up in the grid.

### Screenshots
n/a

### Environment:
 - Device: Iphone X
 - OS: IOS 15.2
 - Version 3.0.0 (92)

### Additional context
n/a

**Comment by TippieCodes** [comment]
Cause of issue has been found:
- The v2 version of the Thalia API only returns the first 50 due to pagination.

**Comment by DeD1rk** [comment]
The food and event admins will also need to get pagination (though since those are for organisers only, it could also be acceptable to just set a very high limit). The api does not allow having no pagination (apparently it defaults to 50), so we do need to explicitly give a limit for the admins in any case.
