### ISSUE TITLE
About is located above the actual settings

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#151]
### Describe the bug
In the settings screen the information about the app is shown above the actual settings. You would expect this to be reversed.

### How to reproduce
1. Go to settings.

### Expected behaviour
About information at the bottom.

### Additional context
Note the examples in the original PR for examples where info is in the settings screen. It is industry standard that this is at the bottom.

**Comment by DeD1rk** [comment]
There's something to be said for moving the card down. That does have a disadvantage: the notification settings are loaded asynchronously, so moving those up would lead to a possibly disturbing stutter when the notification settings appear. 

We could mitigate that by adding a fading and resizing animation around the notification settings, or by having the settings cubit be created upon starting the app, instead of opening the settings screen.

Note that I did ask (though not very clearly) about this in the settings PR. Thinking about it again I think making the settings cubit not lazy would be a quite neat way to move the card down without visual problems, so I'll try that.
