### ISSUE TITLE
Show cancellations and waiting list in admin view

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/Reaxit#179]
### Describe the solution you'd like
Add cancellations and the waiting list in the admin view in separate sections. 

### Motivation
This is useful information for event organizers

### Describe alternatives you've considered
Checking it on the site, but that is the point of the app, to show it in the app.

### Additional context
First the API needs to be updated https://github.com/svthalia/concrexit/issues/2071

**Comment by Jorritboer** [comment]
Already dibsing because this is small enough I can do it and big enough for it to be fun

**Comment by Jorritboer** [comment]
https://github.com/svthalia/concrexit/pull/2203 should allow for this to happen

**Comment by DeD1rk** [comment]
I suppose this has been un-dibsed. Since cancelled/waiting registrations will need to be quite different from normal registrations, I think this would be best using a tab view (filters, such as in a sidebar, would imply the entries to all be similar, but there should never be confusion about which registrations are actually invited and which aren't).
